#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ThuVien")]
	public partial class QLThuVienDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBorrowedBook(BorrowedBook instance);
    partial void UpdateBorrowedBook(BorrowedBook instance);
    partial void DeleteBorrowedBook(BorrowedBook instance);
    partial void InsertTableBook(TableBook instance);
    partial void UpdateTableBook(TableBook instance);
    partial void DeleteTableBook(TableBook instance);
    partial void InsertTransactionHistory(TransactionHistory instance);
    partial void UpdateTransactionHistory(TransactionHistory instance);
    partial void DeleteTransactionHistory(TransactionHistory instance);
    partial void InsertAccount(Account instance);
    partial void UpdateAccount(Account instance);
    partial void DeleteAccount(Account instance);
    #endregion
		
		public QLThuVienDataContext() : 
				base(global::WindowsFormsApp1.Properties.Settings.Default.ThuVienConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLThuVienDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLThuVienDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLThuVienDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLThuVienDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BorrowedBook> BorrowedBooks
		{
			get
			{
				return this.GetTable<BorrowedBook>();
			}
		}
		
		public System.Data.Linq.Table<TableBook> TableBooks
		{
			get
			{
				return this.GetTable<TableBook>();
			}
		}
		
		public System.Data.Linq.Table<TransactionHistory> TransactionHistories
		{
			get
			{
				return this.GetTable<TransactionHistory>();
			}
		}
		
		public System.Data.Linq.Table<Account> Accounts
		{
			get
			{
				return this.GetTable<Account>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BorrowedBook")]
	public partial class BorrowedBook : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_sach;
		
		private string _Ten_sach;
		
		private string _Tac_gia;
		
		private string _Ten_member;
		
		private string _id_member;
		
		private int _So_luong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_sachChanging(string value);
    partial void Onid_sachChanged();
    partial void OnTen_sachChanging(string value);
    partial void OnTen_sachChanged();
    partial void OnTac_giaChanging(string value);
    partial void OnTac_giaChanged();
    partial void OnTen_memberChanging(string value);
    partial void OnTen_memberChanged();
    partial void Onid_memberChanging(string value);
    partial void Onid_memberChanged();
    partial void OnSo_luongChanging(int value);
    partial void OnSo_luongChanged();
    #endregion
		
		public BorrowedBook()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_sach", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_sach
		{
			get
			{
				return this._id_sach;
			}
			set
			{
				if ((this._id_sach != value))
				{
					this.Onid_sachChanging(value);
					this.SendPropertyChanging();
					this._id_sach = value;
					this.SendPropertyChanged("id_sach");
					this.Onid_sachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_sach", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Ten_sach
		{
			get
			{
				return this._Ten_sach;
			}
			set
			{
				if ((this._Ten_sach != value))
				{
					this.OnTen_sachChanging(value);
					this.SendPropertyChanging();
					this._Ten_sach = value;
					this.SendPropertyChanged("Ten_sach");
					this.OnTen_sachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tac_gia", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Tac_gia
		{
			get
			{
				return this._Tac_gia;
			}
			set
			{
				if ((this._Tac_gia != value))
				{
					this.OnTac_giaChanging(value);
					this.SendPropertyChanging();
					this._Tac_gia = value;
					this.SendPropertyChanged("Tac_gia");
					this.OnTac_giaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_member", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Ten_member
		{
			get
			{
				return this._Ten_member;
			}
			set
			{
				if ((this._Ten_member != value))
				{
					this.OnTen_memberChanging(value);
					this.SendPropertyChanging();
					this._Ten_member = value;
					this.SendPropertyChanged("Ten_member");
					this.OnTen_memberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_member", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_member
		{
			get
			{
				return this._id_member;
			}
			set
			{
				if ((this._id_member != value))
				{
					this.Onid_memberChanging(value);
					this.SendPropertyChanging();
					this._id_member = value;
					this.SendPropertyChanged("id_member");
					this.Onid_memberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_So_luong", DbType="Int NOT NULL")]
		public int So_luong
		{
			get
			{
				return this._So_luong;
			}
			set
			{
				if ((this._So_luong != value))
				{
					this.OnSo_luongChanging(value);
					this.SendPropertyChanging();
					this._So_luong = value;
					this.SendPropertyChanged("So_luong");
					this.OnSo_luongChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TableBook")]
	public partial class TableBook : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_sach;
		
		private string _Ten_sach;
		
		private string _Tac_gia;
		
		private System.Nullable<int> _Tong_so_luong;
		
		private System.Nullable<int> _Da_muon;
		
		private System.Nullable<int> _Con_lai;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_sachChanging(string value);
    partial void Onid_sachChanged();
    partial void OnTen_sachChanging(string value);
    partial void OnTen_sachChanged();
    partial void OnTac_giaChanging(string value);
    partial void OnTac_giaChanged();
    partial void OnTong_so_luongChanging(System.Nullable<int> value);
    partial void OnTong_so_luongChanged();
    partial void OnDa_muonChanging(System.Nullable<int> value);
    partial void OnDa_muonChanged();
    partial void OnCon_laiChanging(System.Nullable<int> value);
    partial void OnCon_laiChanged();
    #endregion
		
		public TableBook()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_sach", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_sach
		{
			get
			{
				return this._id_sach;
			}
			set
			{
				if ((this._id_sach != value))
				{
					this.Onid_sachChanging(value);
					this.SendPropertyChanging();
					this._id_sach = value;
					this.SendPropertyChanged("id_sach");
					this.Onid_sachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_sach", DbType="NVarChar(100)")]
		public string Ten_sach
		{
			get
			{
				return this._Ten_sach;
			}
			set
			{
				if ((this._Ten_sach != value))
				{
					this.OnTen_sachChanging(value);
					this.SendPropertyChanging();
					this._Ten_sach = value;
					this.SendPropertyChanged("Ten_sach");
					this.OnTen_sachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tac_gia", DbType="NVarChar(100)")]
		public string Tac_gia
		{
			get
			{
				return this._Tac_gia;
			}
			set
			{
				if ((this._Tac_gia != value))
				{
					this.OnTac_giaChanging(value);
					this.SendPropertyChanging();
					this._Tac_gia = value;
					this.SendPropertyChanged("Tac_gia");
					this.OnTac_giaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tong_so_luong", DbType="Int")]
		public System.Nullable<int> Tong_so_luong
		{
			get
			{
				return this._Tong_so_luong;
			}
			set
			{
				if ((this._Tong_so_luong != value))
				{
					this.OnTong_so_luongChanging(value);
					this.SendPropertyChanging();
					this._Tong_so_luong = value;
					this.SendPropertyChanged("Tong_so_luong");
					this.OnTong_so_luongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Da_muon", DbType="Int")]
		public System.Nullable<int> Da_muon
		{
			get
			{
				return this._Da_muon;
			}
			set
			{
				if ((this._Da_muon != value))
				{
					this.OnDa_muonChanging(value);
					this.SendPropertyChanging();
					this._Da_muon = value;
					this.SendPropertyChanged("Da_muon");
					this.OnDa_muonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Con_lai", DbType="Int")]
		public System.Nullable<int> Con_lai
		{
			get
			{
				return this._Con_lai;
			}
			set
			{
				if ((this._Con_lai != value))
				{
					this.OnCon_laiChanging(value);
					this.SendPropertyChanging();
					this._Con_lai = value;
					this.SendPropertyChanged("Con_lai");
					this.OnCon_laiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TransactionHistory")]
	public partial class TransactionHistory : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _stt;
		
		private string _id_sach;
		
		private string _Ten_sach;
		
		private string _Tac_gia;
		
		private string _id_member;
		
		private string _Ten_member;
		
		private string _Activate;
		
		private System.DateTime _day;
		
		private System.TimeSpan _time;
		
		private int _So_luong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsttChanging(int value);
    partial void OnsttChanged();
    partial void Onid_sachChanging(string value);
    partial void Onid_sachChanged();
    partial void OnTen_sachChanging(string value);
    partial void OnTen_sachChanged();
    partial void OnTac_giaChanging(string value);
    partial void OnTac_giaChanged();
    partial void Onid_memberChanging(string value);
    partial void Onid_memberChanged();
    partial void OnTen_memberChanging(string value);
    partial void OnTen_memberChanged();
    partial void OnActivateChanging(string value);
    partial void OnActivateChanged();
    partial void OndayChanging(System.DateTime value);
    partial void OndayChanged();
    partial void OntimeChanging(System.TimeSpan value);
    partial void OntimeChanged();
    partial void OnSo_luongChanging(int value);
    partial void OnSo_luongChanged();
    #endregion
		
		public TransactionHistory()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stt", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int stt
		{
			get
			{
				return this._stt;
			}
			set
			{
				if ((this._stt != value))
				{
					this.OnsttChanging(value);
					this.SendPropertyChanging();
					this._stt = value;
					this.SendPropertyChanged("stt");
					this.OnsttChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_sach", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string id_sach
		{
			get
			{
				return this._id_sach;
			}
			set
			{
				if ((this._id_sach != value))
				{
					this.Onid_sachChanging(value);
					this.SendPropertyChanging();
					this._id_sach = value;
					this.SendPropertyChanged("id_sach");
					this.Onid_sachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_sach", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Ten_sach
		{
			get
			{
				return this._Ten_sach;
			}
			set
			{
				if ((this._Ten_sach != value))
				{
					this.OnTen_sachChanging(value);
					this.SendPropertyChanging();
					this._Ten_sach = value;
					this.SendPropertyChanged("Ten_sach");
					this.OnTen_sachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tac_gia", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Tac_gia
		{
			get
			{
				return this._Tac_gia;
			}
			set
			{
				if ((this._Tac_gia != value))
				{
					this.OnTac_giaChanging(value);
					this.SendPropertyChanging();
					this._Tac_gia = value;
					this.SendPropertyChanged("Tac_gia");
					this.OnTac_giaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_member", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string id_member
		{
			get
			{
				return this._id_member;
			}
			set
			{
				if ((this._id_member != value))
				{
					this.Onid_memberChanging(value);
					this.SendPropertyChanging();
					this._id_member = value;
					this.SendPropertyChanged("id_member");
					this.Onid_memberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_member", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Ten_member
		{
			get
			{
				return this._Ten_member;
			}
			set
			{
				if ((this._Ten_member != value))
				{
					this.OnTen_memberChanging(value);
					this.SendPropertyChanging();
					this._Ten_member = value;
					this.SendPropertyChanged("Ten_member");
					this.OnTen_memberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Activate", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Activate
		{
			get
			{
				return this._Activate;
			}
			set
			{
				if ((this._Activate != value))
				{
					this.OnActivateChanging(value);
					this.SendPropertyChanging();
					this._Activate = value;
					this.SendPropertyChanged("Activate");
					this.OnActivateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_day", DbType="Date NOT NULL")]
		public System.DateTime day
		{
			get
			{
				return this._day;
			}
			set
			{
				if ((this._day != value))
				{
					this.OndayChanging(value);
					this.SendPropertyChanging();
					this._day = value;
					this.SendPropertyChanged("day");
					this.OndayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_time", DbType="Time NOT NULL")]
		public System.TimeSpan time
		{
			get
			{
				return this._time;
			}
			set
			{
				if ((this._time != value))
				{
					this.OntimeChanging(value);
					this.SendPropertyChanging();
					this._time = value;
					this.SendPropertyChanged("time");
					this.OntimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_So_luong", DbType="Int NOT NULL")]
		public int So_luong
		{
			get
			{
				return this._So_luong;
			}
			set
			{
				if ((this._So_luong != value))
				{
					this.OnSo_luongChanging(value);
					this.SendPropertyChanging();
					this._So_luong = value;
					this.SendPropertyChanged("So_luong");
					this.OnSo_luongChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Account")]
	public partial class Account : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_person;
		
		private string _Username;
		
		private string _Password;
		
		private string _Ten_person;
		
		private string _Gioi_tinh;
		
		private System.DateTime _Birthday_person;
		
		private string _Address;
		
		private string _Contact_Info;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_personChanging(int value);
    partial void Onid_personChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnTen_personChanging(string value);
    partial void OnTen_personChanged();
    partial void OnGioi_tinhChanging(string value);
    partial void OnGioi_tinhChanged();
    partial void OnBirthday_personChanging(System.DateTime value);
    partial void OnBirthday_personChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnContact_InfoChanging(string value);
    partial void OnContact_InfoChanged();
    #endregion
		
		public Account()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_person", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_person
		{
			get
			{
				return this._id_person;
			}
			set
			{
				if ((this._id_person != value))
				{
					this.Onid_personChanging(value);
					this.SendPropertyChanging();
					this._id_person = value;
					this.SendPropertyChanged("id_person");
					this.Onid_personChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_person", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Ten_person
		{
			get
			{
				return this._Ten_person;
			}
			set
			{
				if ((this._Ten_person != value))
				{
					this.OnTen_personChanging(value);
					this.SendPropertyChanging();
					this._Ten_person = value;
					this.SendPropertyChanged("Ten_person");
					this.OnTen_personChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gioi_tinh", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Gioi_tinh
		{
			get
			{
				return this._Gioi_tinh;
			}
			set
			{
				if ((this._Gioi_tinh != value))
				{
					this.OnGioi_tinhChanging(value);
					this.SendPropertyChanging();
					this._Gioi_tinh = value;
					this.SendPropertyChanged("Gioi_tinh");
					this.OnGioi_tinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Birthday_person", DbType="Date NOT NULL")]
		public System.DateTime Birthday_person
		{
			get
			{
				return this._Birthday_person;
			}
			set
			{
				if ((this._Birthday_person != value))
				{
					this.OnBirthday_personChanging(value);
					this.SendPropertyChanging();
					this._Birthday_person = value;
					this.SendPropertyChanged("Birthday_person");
					this.OnBirthday_personChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(50)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contact_Info", DbType="NVarChar(50)")]
		public string Contact_Info
		{
			get
			{
				return this._Contact_Info;
			}
			set
			{
				if ((this._Contact_Info != value))
				{
					this.OnContact_InfoChanging(value);
					this.SendPropertyChanging();
					this._Contact_Info = value;
					this.SendPropertyChanged("Contact_Info");
					this.OnContact_InfoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
